version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root

    volumes:
      - db_volumes

    networks:
      - test-newtwork

  pg_admin:
    image: dpage/pgadmin4
    ports:
      - 4242:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=computer@null.com
      - PGADMIN_DEFAULT_PASSWORD=Testing@123456
    links:
      - db

    networks:
      - test-newtwork

volumes:
  db_volumes:

networks:
  test-newtwork:
    driver: bridge
