name: 'Save problems to db'

on:
  push:
    branches:
      - main

jobs:
  save-to-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-verson: 18.x
          cache: npm
      - name: Install deps
        run: yarn
      - name: create env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo DIRECT_URL=${{ secrets.DIRECT_URL }} >> .env
          echo SHADOW_DATABASE_URL=${{ secrets.SHADOW_DATABASE_URL }} >> .env
          echo UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }} >> .env
          echo UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }} >> .env
          echo "cat .env"
      
#       - name: Run script.
#         run: echo ${{ env.DATABASE_URL }}
#         run: DATABASE_URL=${{ env.DATABASE_URL }} DIRECT_URL=${{ env.DIRECT_URL }} SHADOW_DATABASE_URL=${{ env.SHADOW_DATABASE_URL }} UPSTASH_REDIS_REST_URL=${{env.UPSTASH_REDIS_REST_URL}} UPSTASH_REDIS_REST_TOKEN=${{env.UPSTASH_REDIS_REST_TOKEN}} CI=true yarn save-to-db
