name: 'Save problems to db'

on:
  push:
    branches:
      - main

jobs:
  save-to-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-verson: 18.x
          cache: npm
      - name: Install deps
        run: npm install
      
      - name: Run script.
        run: DATABASE_URL=${{ env.DATABASE_URL }} DIRECT_URL=${{ env.DIRECT_URL }} SHADOW_DATABASE_URL=${{ env.SHADOW_DATABASE_URL }} UPSTASH_REDIS_REST_URL=${{env.UPSTASH_REDIS_REST_URL}} UPSTASH_REDIS_REST_TOKEN=${{env.UPSTASH_REDIS_REST_TOKEN}} CI=true npm run save-to-db
